### ISSUE TITLE
/etc/msmtprc "auth" value is off but SMTP_RELAYHOST_USERNAME was specified

### ISSUE THREAD

**Issue by tasmail** [ugoviti/izpbx#81]
tls_starttls is off also tls is off but SMTP_STARTTLS is true.

**Comment by ugoviti** [comment]
Hi, thank you for your bug report.

fixed in the current izPBX 20.16.15 release

Kind regards

**Comment by frozdbyte** [comment]
I hate to say it, but the issue seems to persist as of the latest version. SMTP_STARTTLS is set to true but auth and tls are still off in msmtprc

![Image](https://github.com/user-attachments/assets/debdd900-3630-4d62-a7cc-78a0bdd3666d)

![Image](https://github.com/user-attachments/assets/4ef31279-1a3b-4d4a-bcfc-d69f0fb3600d)
